// Generates registry.json (consumed by `shadcn build` and by GitHub-address
// installs) and app/opaline.css (the site's copy of the theme tokens).
//
//   REGISTRY_URL  public URL where built items are served (no trailing slash)

import { writeFileSync } from "node:fs"

import { items, keyframes, type Item } from "../registry/index.ts"
import {
  dark,
  fontMono,
  fontSans,
  glassKeys,
  light,
  pick,
} from "../registry/theme.ts"

const REGISTRY_URL = (
  process.env.REGISTRY_URL ?? "https://abhishek-mallick.github.io/opaline/r"
).replace(/\/$/, "")
const HOMEPAGE = REGISTRY_URL.replace(/\/r$/, "")

const url = (name: string) => `${REGISTRY_URL}/${name}.json`

function toRegistryItem(item: Item) {
  const out: Record<string, unknown> = {
    name: item.name,
    type: item.type,
    title: item.title,
    description: item.description,
  }
  if (item.dependencies?.length) out.dependencies = item.dependencies
  const registryDependencies = (item.internal ?? []).map(url)
  if (registryDependencies.length) out.registryDependencies = registryDependencies
  if (item.files.length) out.files = item.files

  if (item.name === "theme") {
    out.cssVars = {
      theme: { "font-sans": fontSans, "font-mono": fontMono },
      light,
      dark,
    }
    out.css = {
      "@layer base": {
        body: {
          "-webkit-font-smoothing": "antialiased",
          "-moz-osx-font-smoothing": "grayscale",
          "letter-spacing": "-0.011em",
          "text-rendering": "optimizeLegibility",
        },
      },
    }
  } else if (item.glass) {
    out.cssVars = { light: pick(light, glassKeys), dark: pick(dark, glassKeys) }
  }

  if (item.keyframes?.length) {
    out.css = Object.fromEntries(
      item.keyframes.map((k) => [`@keyframes ${k}`, keyframes[k]])
    )
  }
  return out
}

const registry = {
  $schema: "https://ui.shadcn.com/schema/registry.json",
  name: "opaline",
  homepage: HOMEPAGE,
  items: [
    ...items.map(toRegistryItem),
    {
      name: "all",
      type: "registry:item",
      title: "Everything",
      description: "The Opaline theme and every component in one install.",
      registryDependencies: items
        .filter((i) => i.category !== "foundation" || i.name === "theme")
        .map((i) => url(i.name)),
    },
  ],
}

writeFileSync("registry.json", JSON.stringify(registry, null, 2) + "\n")

// Site theme stylesheet, generated from the same tokens.
const block = (sel: string, vars: Record<string, string>) =>
  `${sel} {\n${Object.entries(vars)
    .map(([k, v]) => `  --${k}: ${v};`)
    .join("\n")}\n}\n`
const frames = Object.entries(keyframes)
  .map(
    ([name, steps]) =>
      `@keyframes ${name} {\n${Object.entries(steps)
        .map(
          ([step, decl]) =>
            `  ${step} { ${Object.entries(decl)
              .map(([p, v]) => `${p}: ${v};`)
              .join(" ")} }`
        )
        .join("\n")}\n}\n`
  )
  .join("\n")

writeFileSync(
  "app/opaline.css",
  `/* Generated by scripts/generate-registry.mts — do not edit. */\n\n` +
    block("@theme", { "font-sans": fontSans, "font-mono": fontMono }) +
    "\n" +
    block(":root", light) +
    "\n" +
    block(".dark", dark) +
    "\n" +
    frames
)

console.log(`registry.json: ${registry.items.length} items → ${REGISTRY_URL}`)
